set(TOOLCHAIN_PATH "C:/Keil_v5/ARM/ARMCLANG/bin")


if(WIN32)
    set(CMAKE_TOOLCHAIN_SUFFIX ".exe")
endif()

set(CMAKE_TOOLCHAIN_PREFIX "arm")
if(DEFINED TOOLCHAIN_PATH)
    set(CMAKE_TOOLCHAIN_PREFIX "${TOOLCHAIN_PATH}/${CMAKE_TOOLCHAIN_PREFIX}")
endif()

set(CMAKE_C_COMPILER   ${CMAKE_TOOLCHAIN_PREFIX}clang${CMAKE_TOOLCHAIN_SUFFIX})
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})
set(CMAKE_CXX_COMPILER ${CMAKE_TOOLCHAIN_PREFIX}clang${CMAKE_TOOLCHAIN_SUFFIX})
set(CMAKE_C_LINK_EXECUTABLE ${CMAKE_TOOLCHAIN_PREFIX}link${CMAKE_TOOLCHAIN_SUFFIX})
set(CMAKE_ASM_LINK_EXECUTABLE ${CMAKE_TOOLCHAIN_PREFIX}link${CMAKE_TOOLCHAIN_SUFFIX})
set(CMAKE_CXX_LINK_EXECUTABLE ${CMAKE_TOOLCHAIN_PREFIX}link${CMAKE_TOOLCHAIN_SUFFIX})

message(STATUS ${CMAKE_C_COMPILER})

# search for program/library/include in the build host directories
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)